---
- name: Install inotify-tools
  apt:
    name: inotify-tools
    state: present
  become: yes

- name: Create inotify script
  template:
    src: wp-video-watcher.sh.j2
    dest: /usr/local/bin/wp-video-watcher.sh
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Create log file
  file:
    path: "{{ inotify_log_file }}"
    state: touch
    owner: www-data
    group: www-data
    mode: '0644'
  become: yes

- name: Create systemd service
  template:
    src: wp-video-watcher.service.j2
    dest: /etc/systemd/system/wp-video-watcher.service
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload systemd

- name: Enable and start inotify service
  systemd:
    name: wp-video-watcher
    enabled: yes
    state: started
    daemon_reload: yes
  become: yes
